# Bamboo theme
[colors.primary]
background = "#252623"
foreground = "#f1e9d2"

[colors.normal]
black = "#1c1e1b"
red = "#e75a7c"
green = "#8fb573"
yellow = "#dbb651"
blue = "#57a5e5"
magenta = "#aaaaff"
cyan = "#70c2be"
white = "#f1e9dc"

[colors.bright]
black = "#5b5e5a"
red = "#e75a7c"
green = "#8fb573"
yellow = "#dbb651"
blue = "#57a5e5"
magenta = "#aaaaff"
cyan = "#70c2be"
white = "#fff8f0"

[env]
TERM = "xterm-256color"

[font]
normal = { family = "IosevkaTerm Nerd Font" }
bold = { family = "IosevkaTerm Nerd Font" }
italic = { family = "IosevkaTerm Nerd Font" }
size = 9

[window]
padding.x = 14
padding.y = 14
decorations = "None"

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
