# Gruvbox Material Dark theme
[colors.primary]
background = "#282828"
foreground = "#d4be98"

[colors.normal]
black = "#3c3836"
red = "#ea6962"
green = "#a9b665"
yellow = "#d8a657"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#d4be98"

[colors.bright]
black = "#5a524c"
red = "#ea6962"
green = "#a9b665"
yellow = "#d8a657"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#d4be98"

[env]
TERM = "xterm-256color"

[font]
normal = { family = "IosevkaTerm Nerd Font" }
bold = { family = "IosevkaTerm Nerd Font" }
italic = { family = "IosevkaTerm Nerd Font" }
size = 9

[window]
padding.x = 14
padding.y = 14
decorations = "None"

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
