format = "$os$directory$git_branch$git_status$nodejs$python$rust$golang$lua$nix_shell$cmd_duration$line_break$character"

[os]
disabled = false

[os.symbols]
Pop = "ğŸ§ "

[buf]
disabled = true

[character]
error_symbol = "[ó°˜§](bold red)"
success_symbol = "[ó°˜§](bold green)"

[directory]
truncate_to_repo = true
truncation_symbol = "â€¦/"
truncation_length = 1

[dotnet]
detect_files = ["global.json", "Directory.Build.props", "Directory.Build.targets", "Packages.props"]

[git_branch]
symbol = " "
truncation_length = 18

[git_status]
staged = "[âœ“$count](green)"
modified = "[âœ$count](yellow)"
untracked = "[â˜…$count](blue)"
deleted = "[âœ—$count](red)"
conflicted = "[!$count](bold red)"
ahead = "[â†‘$count](cyan)"
behind = "[â†“$count](cyan)"
diverged = "[â†•](cyan)"

[git_commit]
disabled = true

[git_state]

[golang]
symbol = " "

[lua]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = "â¬¢ "

[python]
symbol = " "

[rust]
symbol = " "

[cmd_duration]
min_time = 500
format = "[â³ $duration]($style) "
style = "yellow"

[package]
disabled = true
