format = "$os$directory$git_branch$git_status$nodejs$python$rust$golang$lua$nix_shell$cmd_duration$line_break$character"

# Bamboo color palette
palette = "bamboo"

[palettes.bamboo]
fg = "#f1e9d2"
muted = "#5b5e5a"
orange = "#dbb651"
cyan = "#70c2be"
blue = "#57a5e5"
purple = "#aaaaff"
red = "#e75a7c"
grey = "#5b5e5a"
green = "#8fb573"

[os]
disabled = false
style = "fg:orange"

[os.symbols]
Pop = "ğŸ§ "

[buf]
disabled = true

[character]
error_symbol = "[ó°˜§](bold red)"
success_symbol = "[ó°˜§](bold cyan)"

[directory]
truncate_to_repo = true
truncation_symbol = "â€¦/"
truncation_length = 1
style = "fg:orange bold"

[dotnet]
detect_files = ["global.json", "Directory.Build.props", "Directory.Build.targets", "Packages.props"]

[git_branch]
symbol = " "
truncation_length = 18
style = "fg:purple"

[git_status]
staged = "[âœ“$count](cyan)"
modified = "[âœ$count](orange)"
untracked = "[â˜…$count](blue)"
deleted = "[âœ—$count](red)"
stashed = "[ğŸ“¦](purple)"
conflicted = "[!$count](bold red)"
ahead = "[â†‘$count](cyan)"
behind = "[â†“$count](cyan)"
diverged = "[â†•](cyan)"

[git_commit]
disabled = true

[git_state]

[golang]
symbol = " "
style = "fg:cyan"

[lua]
symbol = " "
style = "fg:blue"

[nix_shell]
symbol = " "
style = "fg:purple"

[nodejs]
symbol = "â¬¢ "
style = "fg:cyan"

[python]
symbol = " "
style = "fg:orange"

[rust]
symbol = " "
style = "fg:orange"

[cmd_duration]
min_time = 500
format = "[â³ $duration]($style) "
style = "fg:muted"

[package]
disabled = true
