format = "$os$directory$git_branch$git_status$nodejs$python$rust$golang$lua$nix_shell$cmd_duration$line_break$character"

[os]
disabled = false

[os.symbols]
Pop = "üêß "

[buf]
disabled = true

[character]
error_symbol = "[Û∞òß](bold red)"
success_symbol = "[Û∞òß](bold green)"

[directory]
truncate_to_repo = false
truncation_symbol = "‚Ä¶/"
fish_style_pwd_dir_length = 1

[dotnet]
detect_files = ["global.json", "Directory.Build.props", "Directory.Build.targets", "Packages.props"]

[git_branch]
symbol = " "
truncation_length = 18

[git_status]
staged = "[+$count](green)"
modified = "[~$count](yellow)"
untracked = "[?$count](blue)"
deleted = "[-$count](red)"
conflicted = "[!$count](bold red)"
ahead = "[‚á°$count](cyan)"
behind = "[‚á£$count](cyan)"
diverged = "[‚áï](cyan)"

[git_commit]
disabled = true

[git_state]

[golang]
symbol = " "

[lua]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = "‚¨¢ "

[python]
symbol = " "

[rust]
symbol = " "

[cmd_duration]
min_time = 500
format = "[‚è≥ $duration]($style) "
style = "yellow"

[package]
disabled = true
